### ISSUE TITLE
Crash if no steps

### ISSUE THREAD

**Issue by DrewMonroe** [YouClid/youclid#77]
The frontend doesn't work properly if there are no steps. If you try to use `<left>` or `<right>`, things disappear, and errors are logged. See `postulate2.html`

**Comment by josephsweeney** [comment]
It looks like the backend outputs a single array if there are no steps? 

<img width="357" alt="screen shot 2018-02-01 at 9 11 06 am" src="https://user-images.githubusercontent.com/8032580/35682780-e5414fe6-072f-11e8-91e1-029a09c9c87a.png">


If there are no steps I think to keep it consistent it should output an array with a single array with all the elements because if there are steps its an array of arrays. So I'm gonna label this backend. @DrewMonroe lemme know if you disagree.

**Comment by josephsweeney** [comment]
Nope this was my b.
