### ISSUE TITLE
Names in text have no correspondence

### ISSUE THREAD

**Issue by josephsweeney** [YouClid/youclid#88]
So in the generated html, some names are of the form `text_center_B` or `text_line_BA` instead of `text_point_B` or `text_line_AB` which the object would imply. I think we should have these be of the form (corresponding with the geometric object) `text_{obj.type.toLowerCase()}_{obj.id}` because otherwise I have to figure out all the potential varieties of names you may generate for a single object.

Let me know if anybody disagrees because the current state of the names feels inconsistent with the geometry data so if there's a rationale behind it I'm open to it.

**Comment by DrewMonroe** [comment]
Nope, that makes perfect sense, it should be an easy thing to fix

**Comment by DrewMonroe** [comment]
I think that the reason that things are like this is due to an inconsistency in how we're naming things. Before we added the `text` keyword argument, `name` served as both the text and as the identifier. So, if you wanted to have `line AB` and `line BA` in the text, you would write that in the markup, and our parsers ordered the points for creating the backend storage so they pointed to the same object. Now, we're using `name` as the identifier for the object, and you can use `text` to replace what shows up in the HTML. So, we just need to unify `name` in the markup and add `text` where we want things to show up differently. It may be worth having a discussion to see if we want something like `line AB` and `line BA` to actually point to the same object, or if they should be two different objects

**Comment by josephsweeney** [comment]
Leaving aside that discussion, I'd say in the current state, the `name` in the text should be the same for both  because there aren't two separate objects for `line AB` and `line BA`.

**Comment by DrewMonroe** [comment]
Yeah, agreed. If we do that, it should fix the issue.
