### ISSUE TITLE
Default Color Should Not Be Related To Type

### ISSUE THREAD

**Issue by saileshsimhadri** [YouClid/youclid#95]
Cycle through colors for each object instead of having default colors by type.

**Comment by DrewMonroe** [comment]
How many colors do you think we need to use to cycle through? My initial thought was going to be to just have a set list of colors, and just iterate through the list, however, this could lead to duplicate colors if we don't have a list of sufficient size. So, either we have a bunch of colors, or we try to make it such that there are not two lines that are the same color, or two points, etc. Of course, the more complex the drawing, the harder this becomes, so we still need a large pallet. Maybe we pseudorandomly choose colors so that there aren't duplicates? Thoughts?
